### ISSUE TITLE
Using lava buckets halts the flow of smelting

### ISSUE THREAD

**Issue by mtango688** [tenplus1/hopper#2]
If you supply lava buckets to the fuel slot of a furnace, the furnace will replace the lava bucket with an empty bucket and remain in that state when the lava has finished being used.

**Comment by tenplus1** [comment]
This isn't a bug, it's a feature of smelting using lava buckets where an empty bucket is returned for the player to remove and use again.

**Comment by mtango688** [comment]
Really? Are you kidding me?

**Comment by tenplus1** [comment]
Many craft recipes, eating replacements and furnace fuel's can return an item on craft/use/burn, it would kinda suck if you placed a bucket of lava and never go the bucket back...  Coalblocks give the same burning time and won't cause a stall in production, same with Ethanol from Farming Redo.

**Comment by mtango688** [comment]
Sorry, I didn't make myself clear. I thought the obvious thing to do would be for the hopper to move the item into storage below, if it discovered something in the fuel slot that wasn't able to be used for fuel.

**Comment by tenplus1** [comment]
I could maybe add a check for empty vessels/buckets and have them move on...
